name: Abismal Release (macOS)

on:
  workflow_dispatch:

jobs:
  build-macos-releases:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Make abismal dependency directories
        run: |
          sudo mkdir -p /opt/abismal/lib
          sudo mkdir -p /opt/abismal/include
      - name: Install dependency headers and static libs
        run: |
          brew install zlib gsl automake
          sudo cp $(brew --prefix zlib)/lib/*.a /opt/abismal/lib
          sudo cp $(brew --prefix gsl)/lib/*.a /opt/abismal/lib
          sudo cp -r $(brew --prefix zlib)/include/* /opt/abismal/include
          sudo cp -r $(brew --prefix gsl)/include/* /opt/abismal/include
      - name: Build and install HTSlib
        run: |
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          autoreconf -i
          mkdir build && cd build
          ../configure \
            --disable-bz2 \
            --disable-libcurl \
            --disable-lzma \
            --disable-ref-cache \
            --without-libdeflate \
            LDADD="-L/usr/local/lib"
          make CFLAGS="-Wall -O2 -fvisibility=hidden" libhts.a
          sudo cp libhts.a /opt/abismal/lib
          sudo cp -r ../htslib /opt/abismal/include
      - name: Build abismal
        run: |
          ls -lh
          ./autogen.sh
          mkdir build && cd build
          ../configure LDFLAGS="-L/opt/abismal/lib" CPPFLAGS="-I/opt/abismal/include"
          make -j4
      - name: Rename the binary
        run: |
          mv abismal/build/abismal abismal_$(uname -m)
      - name: Get version number
        id: vars
        run: |
          awk '/AC_INIT/ {print "vn="$2}' configure.ac | \
            sed "s/\[//; s/\]//; s/,//" >> "$GITHUB_OUTPUT"
          uname -m | awk '{print "arch="$0}' >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload the binary
        uses: actions/upload-artifact@v4
        with:
          name: abismal-${{ steps.vars.outputs.vn }}-${{ matrix.os }}-${{ steps.vars.outputs.arch }}
          path: |
            abismal_${{ steps.vars.outputs.arch }}
  package:
    needs: build-macos-releases
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries
          pattern: abismal-*
          merge-multiple: false
      - name: Create universal binary
        run: |
          lipo -create \
          binaries/abismal-*/abismal_* \
          -output abismal
      - name: Get version number
        id: vn
        run: |
          awk '/AC_INIT/ {print "vn="$2}' configure.ac | \
            sed "s/\[//; s/\]//; s/,//" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload the package files
        uses: actions/upload-artifact@v4
        with:
          name: abismal-${{ steps.vn.outputs.vn }}-macOS
          path: abismal
