name: Abismal distcheck (Ubuntu)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update packages
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y libhts-dev
    - name: Generate configure script
      run: ./autogen.sh
    - name: Generate the Makefile
      run: ./configure
    - name: Distcheck
      run: make -j4 distcheck
