name: Abismal builds on macOS (x86)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Update Homebrew
      run: brew update
    - name: Install autotools
      run: brew install autoconf automake libtool
    - name: Install dependencies
      run: brew install htslib gsl
    - name: Generate configure script
      run: ./autogen.sh
    - name: configure with g++-13
      run: ./configure CXX="g++-13" CPPFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib"
    - name: make
      run: make
